/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: phuongnamng1997 (https://sketchfab.com/phuongnamng1997)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/television-5a45aa7630304b7ebdda5a3b4821660c
title: television
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Television(props) {
  const ref=useRef()
  const { nodes, materials } = useGLTF("/television.gltf");
  useFrame(({ clock }) => {
    ref.current.rotation.y = clock.getElapsedTime()
  })

  return (
    <group {...props} ref={ref} dispose={null}>
      <group  rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.screen}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/television.gltf");
