export const ActionTypes={
    FETCH_MOVIES : 'FETCH_MOVIES',
    FETCH_SECTION_MOVIES : 'FETCH_SECTION_MOVIES',
    FETCH_NEW_MOVIES : 'FETCH_NEW_MOVIES',
    FETCH_POPULAR_MOVIES : 'FETCH_POPULAR_MOVIES',
    FETCH_TREND_MOVIES : 'FETCH_TREND_MOVIES',
    FETCH_SIMILAR_MOVIES : 'FETCH_SIMILAR_MOVIES',
    FETCH_SEARCH_MOVIES : 'FETCH_SEARCH_MOVIES',
    GET_GENRES : 'GET_GENRES',
    SELECTED_MOVIE : 'SELECTED_MOVIE',
    DELETE_SELECTED_MOVIE : 'DELETE_SELECTED_MOVIE',
    DELETE_SECTION_MOVIES : 'DELETE_SECTION_MOVIES',
    DELETE_SEARCH_MOVIE : 'DELETE_SEARCH_MOVIE',
    FETCH_REVIEWS : 'FETCH_REVIEWS',
    DELETE_REVIEWS : 'DELETE_REVIEWS',
    REMOVE_SELECTED_MOVIE : 'REMOVE_SELECTED_MOVIE '
}